version: '3'
services:
  # Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./src/:/var/www/html
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=db"
    networks:
      - laravel

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: nginx_webserver
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - laravel

  # MySQL Database
  db:
    image: mysql:5.7
    container_name: mysql_database
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

# Docker Networks
networks:
  laravel:
    driver: bridge

# Volumes
volumes:
  dbdata:
    driver: local
